# Generated by Django 4.2.1 on 2023-06-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support', models.CharField(default='1,5m+', max_length=55, null=True)),
                ('helped', models.CharField(default='9k+', max_length=55, null=True)),
                ('partner', models.CharField(default='25+', max_length=55, null=True)),
            ],
            options={
                'db_table': 'main_page_fields',
            },
        ),
    ]
