# Generated by Django 4.2.1 on 2023-07-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationDonate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donate_link', models.URLField(default='www', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterDonate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donate_link', models.URLField(default='www', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainDonate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_banner_link', models.URLField(default='www', max_length=255, null=True)),
                ('to_help_link', models.URLField(default='www', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDonate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donate_link', models.URLField(default='www', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsDonate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donate_link', models.URLField(default='www', max_length=255, null=True)),
            ],
        ),
    ]
